# Our base image that conatins OpenJDK



FROM openjdk


# add the fatjar in the image


COPY /target/dockerdemo-0.0.1-SNAPSHOT.jar /

# DEFAULT COMMAND



CMD java -jar /dockerdemo-0.0.1-SNAPSHOT.jar


